version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    dns:
      - 172.68.0.101
    networks:
      pihole_sub:
    
  pihole:
    image: pihole/pihole:latest
    restart: always
    container_name: pihole
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "80:80"
    expose:
      - "80"
      - "443"
      - "53/tcp"
      - "53/udp"
    volumes:
      - ./pihole-data:/etc/pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: 'America/Chicago'
#      - WEBPASSWORD=${PIHOLE_WEBPASS:-SUBFAIL}
    networks:
      pihole_sub:
        ipv4_address: 172.68.0.101
#      default: #this breaks return routing to openvpn

networks:
  pihole_sub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.68.0.0/16